lesson05/Models/DataModels/NhkMember.cs
namespace lesson05.Models.DataModels
{
    public class NhkMember
    {
        public string NhkMemberId { get; set; }
        public string NhkUserName { get; set; }
        public string NhkPassWord { get; set; }
        public string NhkFullName { get; set; }
        public string NhkEmail { get; set; }

    }
}

lesson05/Models/ErrorViewModel.cs
namespace lesson05.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lesson05/Controllers/NhkHomeController.cs
using System.Diagnostics;
using lesson05.Models;
using lesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace lesson05.Controllers
{
    public class NhkHomeController : Controller
    {
        private readonly ILogger<NhkHomeController> _logger;

        public NhkHomeController(ILogger<NhkHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NhkIndex()
        {
            return View();
        }

        public IActionResult NhkAbout()
        {
            NhkMember nhkMember = new NhkMember();
            nhkMember.NhkMemberId = Guid.NewGuid().ToString();
            nhkMember.NhkUserName = "NguyenKien";
            nhkMember.NhkPassWord = "123456";   
            nhkMember.NhkFullName = "Nguyen Hong Kien";
            nhkMember.NhkEmail = "Kientlhb3@gmail.com";
            return View(nhkMember);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lesson05/Controllers/NhkMemberController.cs
using lesson05.Models.DataModels;
using Microsoft.AspNetCore.Mvc;

namespace lesson05.Controllers
{
    public class NhkMemberController : Controller
    {
        private static List<NhkMember> nhkListMembers = new List<NhkMember>
        {
            new NhkMember
            {
                NhkMemberId = "2310900055",
                NhkUserName = "NguyenKien",
                NhkPassWord = "123456",
                NhkFullName = "Nguyen Hong Kien",
                NhkEmail = "Kientlhb3@gmail.com"
            },
            new NhkMember
            {
                NhkMemberId = "M002",
                NhkUserName = "user2",
                NhkPassWord = "pass2",
                NhkFullName = "Tran Thi B",
                NhkEmail = "user2@example.com"
            },
            new NhkMember
            {
                NhkMemberId = "M003",
                NhkUserName = "user3",
                NhkPassWord = "pass3",
                NhkFullName = "Le Van C",
                NhkEmail = "user3@example.com"
            },
            new NhkMember
            {
                NhkMemberId = "M004",
                NhkUserName = "user4",
                NhkPassWord = "pass4",
                NhkFullName = "Pham Thi D",
                NhkEmail = "user4@example.com"
            },
            new NhkMember
            {
                NhkMemberId = "M005",
                NhkUserName = "user5",
                NhkPassWord = "pass5",
                NhkFullName = "Hoang Van E",
                NhkEmail = "user5@example.com"
            }
        };
        public IActionResult NhkIndex()
        {
            return View(nhkListMembers);
        }
    }
}

lesson05/Views/NhkHome/NhkAbout.cshtml
@{
    ViewData["Title"] = "Thong Tin Sinh Vien";
}
<div class="alert alert-info">
<h1>@ViewData["Title"]</h1>
<hr/>
    <p>Member Id: @Model.NhkMemberId</p>
    <p>Member UserName: @Model.NhkUserName</p>
    <p>Member PassWord: @Model.NhkPassWord</p>
    <p>Member FullName: @Model.NhkFullName</p>
    <p>Member Email: @Model.NhkEmail</p>
</div>

lesson05/Views/NhkHome/NhkIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome,Nguyen Hong Kien</h1>

    
</div>

lesson05/Views/NhkMember/NhkIndex.cshtml
@model IEnumerable<lesson05.Models.DataModels.NhkMember>;
@{
    ViewData["Title"] = "NhkIndex";
}

<h1>Danh Sach Member</h1>
<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Member Id</th>
			<th>Member UserName</th>
			<th>Member PassWord</th>
			<th>Member FullName</th>
			<th>Member Email</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var nhkItem in Model)
		{
			<tr>
				<td>@nhkItem.NhkMemberId</td>
				<td>@nhkItem.NhkUserName</td>
				<td>@nhkItem.NhkPassWord</td>
				<td>@nhkItem.NhkFullName</td>
				<td>@nhkItem.NhkEmail</td>
			</tr>
		}
	</tbody>	

lesson05/Views/Shared/_NhkLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lesson05</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lesson05.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
		@Html.Partial("_NhkNavBar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - lesson05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lesson05/Views/Shared/_NhkNavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="NhkHome" asp-action="NhkIndex">lesson05
            - Nguyen Hong Kien
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NhkHome" asp-action="NhkIndex">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NhkHome" asp-action="NhkAbout">Thong tin sinh vien</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NhkMember" asp-action="NhkIndex">Danh sach sinh vien</a>
                </li>
            </ul>
        </div>
    </div>
</nav>